const GET_POPULAR_MOVIES_REQUEST = "GET_POPULAR_MOVIES_REQUEST";
const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
const RATE_MOVIE_REQUEST = "RATE_MOVIE_REQUEST";
const GET_POPULAR_MOVIES_SUCCESS = "GET_POPULAR_MOVIES_SUCCESS";
const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
const RATE_MOVIE_SUCCESS = "RATE_MOVIE_SUCCESS";
const GET_POPULAR_MOVIES_FAILURE = "GET_POPULAR_MOVIES_FAILURE";
const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE";
const RATE_MOVIE_FAILURE = "RATE_MOVIE_FAILURE";

export {
  GET_POPULAR_MOVIES_REQUEST,
  SEARCH_MOVIES_REQUEST,
  RATE_MOVIE_REQUEST,
  GET_POPULAR_MOVIES_SUCCESS,
  SEARCH_MOVIES_SUCCESS,
  RATE_MOVIE_SUCCESS,
  GET_POPULAR_MOVIES_FAILURE,
  SEARCH_MOVIES_FAILURE,
  RATE_MOVIE_FAILURE,
};
