const GET_GUEST_SESSION_REQUEST = "GET_GUEST_SESSION_REQUEST";
const GET_GUEST_SESSION_SUCCESS = "GET_GUEST_SESSION_SUCCESS";
const GET_GUEST_SESSION_ERROR = "GET_GUEST_SESSION_ERROR";
export {
  GET_GUEST_SESSION_REQUEST,
  GET_GUEST_SESSION_SUCCESS,
  GET_GUEST_SESSION_ERROR,
};
